--users 

insert into User (email, password_hash, role) values ('aorrom0@redcross.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('mcoughtrey1@163.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('twhotton2@mozilla.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('tcredland3@flickr.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('cbeacom4@google.com.hk', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('lhaxbie5@newyorker.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('megerton6@nymag.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('edeakan7@geocities.jp', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('ameaker8@bigcartel.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('sblum9@list-manage.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('cchatteya@lycos.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('pkelkb@timesonline.co.uk', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('dmixturec@nytimes.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('elillgardd@apache.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('zbullere@weebly.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('echarlesf@bloglovin.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('tmoroneyg@ebay.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('ctilneyh@about.me', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('kcaulketi@w3.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('ihawtonj@topsy.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('ccalderonk@ucsd.edu', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('lpriterl@washington.edu', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('kkindleysidesm@blogger.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('rduern@fda.gov', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('zjensono@github.io', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('rmasdenp@spiegel.de', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('ndickq@howstuffworks.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('agidneyr@skype.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('washwoods@wikispaces.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('nwoltont@netscape.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('jbohlingu@washington.edu', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('lpickerillv@hugedomains.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('ebrettellw@youtu.be', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('csherryx@marriott.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('vknotty@cisco.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('dlongstreetz@bravesites.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('jmegany10@wix.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('jcleare11@techcrunch.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('cashbolt12@yale.edu', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('alorait13@google.fr', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('rbazoge14@goo.gl', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('mdeeley15@alexa.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('kstelli16@360.cn', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('efright17@apache.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('cricciardi18@nationalgeographic.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('jcutriss19@rakuten.co.jp', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('vdenham1a@newyorker.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('pgilders1b@ezinearticles.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('hbim1c@prnewswire.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('tgreenrde1d@craigslist.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('vhearse1e@eepurl.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('tlittlemore1f@hibu.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('khastilow1g@addtoany.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('bjollands1h@soup.io', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('sgregg1i@economist.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('ccreffield1j@godaddy.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('kdedantesie1k@sohu.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('dpaternoster1l@vistaprint.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('fcornilleau1m@myspace.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('scoombs1n@spiegel.de', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('densten1o@slashdot.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('clowell1p@wikipedia.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('llampitt1q@opera.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('mshill1r@imageshack.us', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('blivings1s@aboutads.info', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('csanches1t@spotify.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('gloughhead1u@ucoz.ru', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('mhaswell1v@moonfruit.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('mhiseman1w@bbc.co.uk', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('nfiddiman1x@narod.ru', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('hupstone1y@google.it', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('dsnead1z@wikia.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('cruddle20@cisco.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('acrunkhurn21@redcross.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('lgillet22@sfgate.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('fskein23@flavors.me', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('chimsworth24@moonfruit.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('ssievewright25@yahoo.co.jp', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('cglazzard26@so-net.ne.jp', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('asheed27@g.co', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('rroylance28@nyu.edu', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('jspurrior29@cocolog-nifty.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('lclendening2a@lulu.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('oixer2b@barnesandnoble.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('lfrane2c@nature.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('iclouter2d@nba.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('whabens2e@furl.net', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('adrejer2f@about.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('rcoddrington2g@cloudflare.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('rpetto2h@tinypic.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('ncholwell2i@va.gov', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('jhillitt2j@jigsy.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('dbeange2k@cisco.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('cthody2l@unesco.org', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('nkempster2m@constantcontact.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('okernoghan2n@artisteer.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('abernardon2o@amazon.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');
insert into User (email, password_hash, role) values ('hhealing2p@newsvine.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team member');
insert into User (email, password_hash, role) values ('cmacallen2q@hugedomains.com', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Team leader');
insert into User (email, password_hash, role) values ('shartman2r@usgs.gov', '$2a$04$0xcYFrZmcY/AWuVhqq3ZRuOKJeRO5ahEdINpqOU0KOiLZjGF3Rn5m', 'Product owner');

--feature requests

insert into Feature_Request (user_id, name, description) values (3, 'Team-oriented homogeneous access', 'Down-sized');
insert into Feature_Request (user_id, name, description) values (6, 'Cross-group static open architecture', 'extranet');
insert into Feature_Request (user_id, name, description) values (2, 'Stand-alone upward-trending definition', 'Virtual');
insert into Feature_Request (user_id, name, description) values (8, 'Organic cohesive collaboration', 'paradigm');
insert into Feature_Request (user_id, name, description) values (6, 'Automated global system engine', 'Assimilated');
insert into Feature_Request (user_id, name, description) values (3, 'Managed incremental installation', 'intermediate');
insert into Feature_Request (user_id, name, description) values (6, 'Digitized directional knowledge base', 'Innovative');
insert into Feature_Request (user_id, name, description) values (6, 'Decentralized tertiary solution', 'logistical');
insert into Feature_Request (user_id, name, description) values (2, 'Multi-channelled bandwidth-monitored standardization', '24/7');
insert into Feature_Request (user_id, name, description) values (3, 'Synergized human-resource forecast', 'data-warehouse');
insert into Feature_Request (user_id, name, description) values (2, 'Programmable mobile groupware', 'optimizing');
insert into Feature_Request (user_id, name, description) values (8, 'Innovative foreground frame', 'discrete');
insert into Feature_Request (user_id, name, description) values (3, 'Customizable exuding moratorium', 'Reverse-engineered');
insert into Feature_Request (user_id, name, description) values (3, 'Distributed radical complexity', 'multi-state');
insert into Feature_Request (user_id, name, description) values (2, 'Grass-roots scalable matrix', 'Integrated');

--sprints

insert into Sprint (name) values ('Goldenrod');
insert into Sprint (name) values ('Teal');
insert into Sprint (name) values ('Fuscia');
insert into Sprint (name) values ('Maroon');

--stories

insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (1, 1, 1, 'P', 'Suspendisse ornare consequat lectus.', 'global');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (2, 1, 2, 'P', 'In blandit ultrices enim.', 'infrastructure');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (3, 10, 3, 'P', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'initiative');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (4, 12, 4, 'P', 'Proin eu mi.', 'budgetary management');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (5, 9, 1, 'P', 'Proin eu mi.', 'Decentralized');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (6, 9, 2, 'P', 'Etiam justo.', 'moratorium');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (7, 12, 3, 'P', 'Etiam faucibus cursus urna.', 'attitude');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (8, 10, 4, 'P', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'solution');

insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (1, 1, 1, 'I', 'Suspendisse ornare consequat lectus.', 'global');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (2, 1, 2, 'I', 'In blandit ultrices enim.', 'infrastructure');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (4, 12, 4, 'I', 'Proin eu mi.', 'budgetary management');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (6, 9, 2, 'I', 'Etiam justo.', 'moratorium');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (7, 12, 3, 'I', 'Etiam faucibus cursus urna.', 'attitude');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (8, 10, 4, 'I', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'solution');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (2, 1, 2, 'I', 'In blandit ultrices enim.', 'infrastructure');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (3, 10, 3, 'I', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'initiative');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (5, 9, 1, 'I', 'Proin eu mi.', 'Decentralized');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (6, 9, 2, 'I', 'Etiam justo.', 'moratorium');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (8, 10, 4, 'I', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'solution');

insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (1, 1, 1, 'C', 'Suspendisse ornare consequat lectus.', 'global');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (2, 1, 2, 'C', 'In blandit ultrices enim.', 'infrastructure');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (3, 10, 3, 'C', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'initiative');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (5, 9, 1, 'C', 'Proin eu mi.', 'Decentralized');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (6, 9, 2, 'C', 'Etiam justo.', 'moratorium');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (7, 12, 3, 'C', 'Etiam faucibus cursus urna.', 'attitude');

insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (1, 1, 1, 'A', 'Suspendisse ornare consequat lectus.', 'global');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (4, 12, 4, 'A', 'Proin eu mi.', 'budgetary management');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (8, 10, 4, 'A', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'solution');
insert into Story (feature_id, user_id, sprint_id, story_status_id, name, description) values (8, 10, 4, 'A', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'solution');
