--users
insert into User (email, password_hash, role) values ('nlunam0@tinypic.com', 'Whl9MF6j', 'Team member');
insert into User (email, password_hash, role) values ('credihalgh1@umich.edu', 'kqMN4pdlCLwl', 'Product owner');
insert into User (email, password_hash, role) values ('bwiskar2@quantcast.com', 'MTDeu2zO', 'Product owner');
insert into User (email, password_hash, role) values ('jwinchcombe3@ustream.tv', 'JOekUzR', 'Team leader');
insert into User (email, password_hash, role) values ('acuttin4@pen.io', 'CJkYWEF', 'Product owner');
insert into User (email, password_hash, role) values ('htabbitt5@mozilla.com', '56LLWO0', 'Product owner');
insert into User (email, password_hash, role) values ('acrallan6@ebay.co.uk', 'hY9NIoLB7Rs', 'Team leader');
insert into User (email, password_hash, role) values ('ssehorsch7@fema.gov', 'kuip861161g', 'Product owner');
insert into User (email, password_hash, role) values ('tbreakspear8@wired.com', '4zuh8r', 'Team member');
insert into User (email, password_hash, role) values ('abuckeridge9@histats.com', 'cqqgYz6r', 'Team member');
insert into User (email, password_hash, role) values ('sdomonia@uiuc.edu', 'rEbI4s', 'Product owner');
insert into User (email, password_hash, role) values ('tmackleyb@issuu.com', 'oYWt2KTpAAnJ', 'Team member');
insert into User (email, password_hash, role) values ('mprewerc@yolasite.com', 'oNmiwedA', 'Team leader');
insert into User (email, password_hash, role) values ('llookd@oracle.com', '6BMbsVovp', 'Product owner');
insert into User (email, password_hash, role) values ('ctale@imageshack.us', '9SUJ413', 'Team member');
insert into User (email, password_hash, role) values ('nabdyf@blinklist.com', 'qGw1cx', 'Team member');
insert into User (email, password_hash, role) values ('bpenhaligong@ask.com', 'dtt6NNkK1ow', 'Product owner');
insert into User (email, password_hash, role) values ('fdineharth@blog.com', '3C0uPq5AwKrD', 'Product owner');
insert into User (email, password_hash, role) values ('rivashnyovi@ca.gov', 'Hh2Orz3BT3s', 'Team leader');
insert into User (email, password_hash, role) values ('tbridgewoodj@rakuten.co.jp', 'qcjGZwGW', 'Team leader');
insert into User (email, password_hash, role) values ('dpawelekk@surveymonkey.com', 'ZPs7fXINoW1m', 'Product owner');
insert into User (email, password_hash, role) values ('dbestarl@illinois.edu', 'T1VYbnL', 'Team leader');
insert into User (email, password_hash, role) values ('gquarmbym@pinterest.com', 'kxdvpb', 'Product owner');
insert into User (email, password_hash, role) values ('dlegrandn@gnu.org', '9xLHxis3FfZa', 'Team leader');
insert into User (email, password_hash, role) values ('mclaypoolo@cyberchimps.com', 'X7Qxlz1mVH6', 'Product owner');
insert into User (email, password_hash, role) values ('dklempkep@gnu.org', 'TknDYzj', 'Product owner');
insert into User (email, password_hash, role) values ('tcordelleq@netlog.com', 'Yra99lWnB4T', 'Team member');
insert into User (email, password_hash, role) values ('ethwaiter@canalblog.com', 'J2jJyyZXhLn', 'Team member');
insert into User (email, password_hash, role) values ('jharlocks@sciencedaily.com', 'YYPxsoN', 'Team member');
insert into User (email, password_hash, role) values ('jpietert@com.com', 'XBex3jtnChQ', 'Product owner');
insert into User (email, password_hash, role) values ('zlabdonu@nps.gov', 'aFlfKm6DvYtJ', 'Product owner');
insert into User (email, password_hash, role) values ('dantonomoliv@cdbaby.com', 'dgMwpUPUJ', 'Team member');
insert into User (email, password_hash, role) values ('lduffriew@discovery.com', 'Zpa6oYEIOfNP', 'Team member');
insert into User (email, password_hash, role) values ('pseeleyx@quantcast.com', '74dWwXP3BSzr', 'Team member');
insert into User (email, password_hash, role) values ('dallridgey@chicagotribune.com', 'ecESj4sZm', 'Team member');
insert into User (email, password_hash, role) values ('rgunnz@hc360.com', 'FkdTrNVBmjO', 'Team leader');
insert into User (email, password_hash, role) values ('bswires10@pinterest.com', 'd9aUii', 'Team member');
insert into User (email, password_hash, role) values ('vrentalll11@hubpages.com', 'CvDYL6', 'Team member');
insert into User (email, password_hash, role) values ('gjanczak12@usnews.com', '7WcfDAI', 'Product owner');
insert into User (email, password_hash, role) values ('bionn13@toplist.cz', 'XdWQ7Czy', 'Product owner');
insert into User (email, password_hash, role) values ('nladen14@hhs.gov', '2XiwkY9yjpq', 'Team leader');
insert into User (email, password_hash, role) values ('clamps15@360.cn', 'QV3of8gXB', 'Team member');
insert into User (email, password_hash, role) values ('ddericot16@parallels.com', 'Vx9mhka6jsLd', 'Product owner');
insert into User (email, password_hash, role) values ('cscarth17@typepad.com', '3BI429qgLVUK', 'Team member');
insert into User (email, password_hash, role) values ('mgrogan18@omniture.com', 'eqpaPfdcnrw', 'Team member');
insert into User (email, password_hash, role) values ('bgleave19@hibu.com', 'ITdkBGmz', 'Team member');
insert into User (email, password_hash, role) values ('kwalrond1a@thetimes.co.uk', 'Dx8vmm8j6i', 'Product owner');
insert into User (email, password_hash, role) values ('millingsworth1b@amazon.de', 'NdzTAGkg', 'Team member');
insert into User (email, password_hash, role) values ('alarkins1c@businessweek.com', 'IxIwyP6Ey', 'Product owner');
insert into User (email, password_hash, role) values ('obeine1d@51.la', 'kgZRgsQvFXS', 'Product owner');
insert into User (email, password_hash, role) values ('sbinding1e@sciencedaily.com', 'wCBZDfkV', 'Team member');
insert into User (email, password_hash, role) values ('kgoing1f@globo.com', 'ux1S5ru', 'Team member');
insert into User (email, password_hash, role) values ('ebarkworth1g@usa.gov', 'eFanDxWW6Oi', 'Product owner');
insert into User (email, password_hash, role) values ('nnaulty1h@ifeng.com', 'Ezmushlv', 'Team leader');
insert into User (email, password_hash, role) values ('ntoffetto1i@microsoft.com', 'oahD5TpvDMGJ', 'Team member');
insert into User (email, password_hash, role) values ('edavion1j@deviantart.com', '975fyr0w', 'Team member');
insert into User (email, password_hash, role) values ('swillgrass1k@parallels.com', 'mYbnQLaE', 'Team leader');
insert into User (email, password_hash, role) values ('edrinkhall1l@admin.ch', 'zhUhrh1XP5j', 'Team member');
insert into User (email, password_hash, role) values ('ctrousdale1m@hexun.com', '4HpwWpmTHH1', 'Team member');
insert into User (email, password_hash, role) values ('dbotham1n@psu.edu', 'Lld5FrM', 'Team leader');
insert into User (email, password_hash, role) values ('gschurig1o@google.co.uk', 'qED6Cs', 'Team member');
insert into User (email, password_hash, role) values ('sbeardshall1p@ted.com', 'wtAqAXUKyWfQ', 'Team leader');
insert into User (email, password_hash, role) values ('alanon1q@slate.com', 'JN8NdbKw', 'Product owner');
insert into User (email, password_hash, role) values ('ctempest1r@virginia.edu', 'Z7tUnXuX7', 'Team leader');
insert into User (email, password_hash, role) values ('bocanavan1s@altervista.org', 'rTbLIJ9Y', 'Team leader');
insert into User (email, password_hash, role) values ('sfonzone1t@newsvine.com', '1oiNqe', 'Team leader');
insert into User (email, password_hash, role) values ('kwilloughway1u@drupal.org', 'w30dsJypYe6', 'Product owner');
insert into User (email, password_hash, role) values ('cbinge1v@bandcamp.com', 'EEaV4M', 'Product owner');
insert into User (email, password_hash, role) values ('fstile1w@yellowpages.com', 'Ymg613', 'Product owner');
insert into User (email, password_hash, role) values ('mnormant1x@hostgator.com', 'xxIlkI1T', 'Team member');
insert into User (email, password_hash, role) values ('gmacmanus1y@unblog.fr', 'Ds6zsM8S', 'Product owner');
insert into User (email, password_hash, role) values ('mcakebread1z@boston.com', 'sHegPz4sV9r', 'Product owner');
insert into User (email, password_hash, role) values ('mszymonowicz20@jugem.jp', 'dt71jxWz7IiH', 'Product owner');
insert into User (email, password_hash, role) values ('fjossel21@github.io', 'B6uvG5Knp6Y', 'Team leader');
insert into User (email, password_hash, role) values ('bgrishanov22@usgs.gov', 'Wo0H0Vf', 'Team leader');
insert into User (email, password_hash, role) values ('jdradey23@prnewswire.com', 'ICKwQu2hB', 'Team member');
insert into User (email, password_hash, role) values ('tcoxall24@tumblr.com', 'NQjq2bX', 'Product owner');
insert into User (email, password_hash, role) values ('llawless25@admin.ch', 'e551sv5', 'Team leader');
insert into User (email, password_hash, role) values ('cwiffield26@cisco.com', 'J4hlAoroES', 'Team member');
insert into User (email, password_hash, role) values ('rmacklam27@ted.com', '6vKdVI', 'Team member');
insert into User (email, password_hash, role) values ('dbattisson28@xrea.com', '3YjWI1t', 'Team member');
insert into User (email, password_hash, role) values ('smorrow29@cam.ac.uk', 'UpCa2ob7Bi', 'Team leader');
insert into User (email, password_hash, role) values ('idenzey2a@ucoz.com', 'v4hUaiflYy', 'Product owner');
insert into User (email, password_hash, role) values ('dpaszek2b@fastcompany.com', 'XsUaBNtIOZO4', 'Product owner');
insert into User (email, password_hash, role) values ('ahabbema2c@howstuffworks.com', '0LBRNpWjXYp', 'Product owner');
insert into User (email, password_hash, role) values ('bferencowicz2d@elpais.com', 'caMKvzb3kRNo', 'Team leader');
insert into User (email, password_hash, role) values ('mkolczynski2e@icq.com', '0hWfMf', 'Product owner');
insert into User (email, password_hash, role) values ('btruitt2f@dyndns.org', '4J1IjOTLTM9M', 'Team leader');
insert into User (email, password_hash, role) values ('phaulkham2g@economist.com', 'p3xnLA3w', 'Team leader');
insert into User (email, password_hash, role) values ('mperegrine2h@un.org', 'GMBvS4is2fUG', 'Team leader');
insert into User (email, password_hash, role) values ('pmellon2i@google.nl', 'Ji79MVdpMj', 'Team leader');
insert into User (email, password_hash, role) values ('kessel2j@com.com', 'UgVhY6MQ', 'Team member');
insert into User (email, password_hash, role) values ('htournay2k@imgur.com', 'JaG1G34s', 'Team member');
insert into User (email, password_hash, role) values ('hbarnewille2l@army.mil', 'olBj0Iy2YSz', 'Product owner');
insert into User (email, password_hash, role) values ('ftiley2m@jigsy.com', 'UtJMqjnTnZ', 'Team member');
insert into User (email, password_hash, role) values ('vcrumbie2n@weather.com', 'xu2Xz1', 'Product owner');
insert into User (email, password_hash, role) values ('rhyett2o@ucla.edu', 'ZQlnfO2', 'Team leader');
insert into User (email, password_hash, role) values ('rdunguy2p@printfriendly.com', 'O9ZZ0S', 'Team member');
insert into User (email, password_hash, role) values ('lyard2q@redcross.org', 'YzObGd', 'Product owner');
insert into User (email, password_hash, role) values ('clauritzen2r@irs.gov', 'j6OGnj9gWe', 'Team leader');

--feature requests
insert into Feature_Request (user_id, name, description) values (3, 'Team-oriented homogeneous access', 'Down-sized');
insert into Feature_Request (user_id, name, description) values (6, 'Cross-group static open architecture', 'extranet');
insert into Feature_Request (user_id, name, description) values (2, 'Stand-alone upward-trending definition', 'Virtual');
insert into Feature_Request (user_id, name, description) values (8, 'Organic cohesive collaboration', 'paradigm');
insert into Feature_Request (user_id, name, description) values (6, 'Automated global system engine', 'Assimilated');
insert into Feature_Request (user_id, name, description) values (3, 'Managed incremental installation', 'intermediate');
insert into Feature_Request (user_id, name, description) values (6, 'Digitized directional knowledge base', 'Innovative');
insert into Feature_Request (user_id, name, description) values (6, 'Decentralized tertiary solution', 'logistical');
insert into Feature_Request (user_id, name, description) values (2, 'Multi-channelled bandwidth-monitored standardization', '24/7');
insert into Feature_Request (user_id, name, description) values (3, 'Synergized human-resource forecast', 'data-warehouse');
insert into Feature_Request (user_id, name, description) values (2, 'Programmable mobile groupware', 'optimizing');
insert into Feature_Request (user_id, name, description) values (8, 'Innovative foreground frame', 'discrete');
insert into Feature_Request (user_id, name, description) values (3, 'Customizable exuding moratorium', 'Reverse-engineered');
insert into Feature_Request (user_id, name, description) values (3, 'Distributed radical complexity', 'multi-state');
insert into Feature_Request (user_id, name, description) values (2, 'Grass-roots scalable matrix', 'Integrated');

--sprints
insert into Sprint (name) values ('Goldenrod');
insert into Sprint (name) values ('Teal');
insert into Sprint (name) values ('Fuscia');
insert into Sprint (name) values ('Maroon');

--stories
insert into Story (feature_id, user_id, sprint_id, name, description) values (1, 1, 1, 'Suspendisse ornare consequat lectus.', 'global');
insert into Story (feature_id, user_id, sprint_id, name, description) values (2, 1, 2, 'In blandit ultrices enim.', 'infrastructure');
insert into Story (feature_id, user_id, sprint_id, name, description) values (3, 10, 3, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'initiative');
insert into Story (feature_id, user_id, sprint_id, name, description) values (4, 12, 4, 'Proin eu mi.', 'budgetary management');
insert into Story (feature_id, user_id, sprint_id, name, description) values (5, 9, 1, 'Proin eu mi.', 'Decentralized');
insert into Story (feature_id, user_id, sprint_id, name, description) values (6, 9, 2, 'Etiam justo.', 'moratorium');
insert into Story (feature_id, user_id, sprint_id, name, description) values (7, 12, 3, 'Etiam faucibus cursus urna.', 'attitude');
insert into Story (feature_id, user_id, sprint_id, name, description) values (8, 10, 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'solution');
